encoding: "utf-8"
exclude: ['Gemfile', 'Gemfile.lock']
title: Akademie f端r Religionslehre
email: info@akademie-fuer-religionslehre.de
description: Akademie f端r Religionslehre - Zentrum f端r nicht bekenntnisgebundene Theologie in Senden bei M端nster
url: "http://www.akademie-fuer-religionslehre.de"
defaults:
  -
    values:
      layout: 'default'